<?php

return [
    'call_centers' => [
        'app_uuid' => env('CALL_CENTER_APP_UUID', '95788e50-9500-079e-2807-fd530b0ea370'),
    ],
    'conferences' => [
        'app_uuid' => env('CONFERENCE_APP_UUID', 'b81412e8-7253-91f4-e48e-42fc2c9a38d9'),
    ],
    'conference_controls' => [
        'app_uuid' => env('CONFERENCE_CONTROL_APP_UUID', 'e1ad84a2-79e1-450c-a5b1-7507a043e048'),
        'controls' => [
            [
                'control_name' => 'moderator',
                'control_enabled' => 'true',
                'control_description' => 'Controls for Conference Moderators',
                'details' => [
                    [
                        'control_digits' => '*',
                        'control_action' => 'execute_application',
                        'control_data' => 'lua app/conference_center/resources/scripts/unmute.lua non_moderator',
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '*',
                        'control_action' => 'deaf mute',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '0',
                        'control_action' => 'execute_application',
                        'control_data' => 'lua app/conference_center/resources/scripts/mute.lua non_moderator',
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '1',
                        'control_action' => 'vol talk dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '2',
                        'control_action' => 'vol talk zero',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '3',
                        'control_action' => 'vol talk up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '4',
                        'control_action' => 'vol listen dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '5',
                        'control_action' => 'vol listen zero',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '6',
                        'control_action' => 'vol listen up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '7',
                        'control_action' => 'energy dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '8',
                        'control_action' => 'energy equ',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '9',
                        'control_action' => 'energy up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                ],
            ],
            [
                'control_name' => 'page',
                'control_enabled' => 'true',
                'control_description' => 'Controls for Conference Pagers',
                'details' => [
                    [
                        'control_digits' => '0',
                        'control_action' => 'mute',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '1',
                        'control_action' => 'vol talk dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '2',
                        'control_action' => 'vol talk zero',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '3',
                        'control_action' => 'vol talk up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '4',
                        'control_action' => 'vol listen dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '5',
                        'control_action' => 'vol listen zero',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '6',
                        'control_action' => 'vol listen up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '7',
                        'control_action' => 'energy dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '8',
                        'control_action' => 'energy equ',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '9',
                        'control_action' => 'energy up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                ],
            ],
            [
                'control_name' => 'default',
                'control_enabled' => 'true',
                'control_description' => 'Default Controls for Conferences',
                'details' => [
                    [
                        'control_digits' => '1',
                        'control_action' => 'vol talk dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '2',
                        'control_action' => 'vol talk zero',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '3',
                        'control_action' => 'vol talk up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '4',
                        'control_action' => 'vol listen dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '5',
                        'control_action' => 'vol listen zero',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '6',
                        'control_action' => 'vol listen up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '7',
                        'control_action' => 'energy dn',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '8',
                        'control_action' => 'energy equ',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                    [
                        'control_digits' => '9',
                        'control_action' => 'energy up',
                        'control_data' => null,
                        'control_enabled' => 'true',
                    ],
                ],
            ]
        ],
    ],
    'conference_profiles' => [
        'app_uuid' => env('CONFERENCE_PROFILE_APP_UUID', 'c33e2c2a-847f-44c1-8c0d-310df5d65ba9'),
        'profiles' => [
            [
                'profile_name' => 'cdquality',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for CD quality',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'auto-gain-level',
                        'profile_param_value' => '0',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-controls',
                        'profile_param_value' => 'default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'true',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '15',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '10',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moderator-controls',
                        'profile_param_value' => 'moderator',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => 'local_stream://default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                    'profile_param_name' => 'rate',
                    'profile_param_value' => '48000',
                    'profile_param_enabled' => 'true',
                    'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'default',
                'profile_enabled' => 'true',
                'profile_description' => 'Default settings',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'auto-gain-level',
                        'profile_param_value' => '0',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-controls',
                        'profile_param_value' => 'default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                        ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                        ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'cdr-log-dir',
                        'profile_param_value' => 'auto',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'true',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '15',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moderator-controls',
                        'profile_param_value' => 'moderator',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => 'local_stream://default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '8000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'page',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for paging',
                'params' => [
                    [
                        'profile_param_name' => 'caller-controls',
                        'profile_param_value' => 'page',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'true',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '300',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moderator-controls',
                        'profile_param_value' => 'moderator',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '8000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'terminate-on-silence',
                        'profile_param_value' => '30',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'sla',
                'profile_enabled' => 'true',
                'profile_description' => null,
                'params' => [
                    [
                        'profile_param_name' => 'caller-controls',
                        'profile_param_value' => 'none',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'true',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '200',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => 'silence',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '16000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'ultrawideband',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for Ultra Wideband',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'auto-gain-level',
                        'profile_param_value' => '0',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-controls',
                        'profile_param_value' => 'default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'true',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '15',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moderator-controls',
                        'profile_param_value' => 'moderator',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => 'local_stream://default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '32000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'video-mcu-stereo',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for MCU Stereo',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => '$${outbound_caller_name}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => '$${outbound_caller_id}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'channels',
                        'profile_param_value' => '2',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'false',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'conference-flags',
                        'profile_param_value' => 'livearray-json-status|json-events|video-floor-only|rfc-4579|livearray-sync|minimize-video-encoding|manage-inbound-video-bitrate|video-required-for-canvas|video-mute-exit-canvas|mute-detect',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => '$${domain}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '200',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => '$${hold_music}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '48000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-auto-floor-msec',
                        'profile_param_value' => '1000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-bgcolor',
                        'profile_param_value' => '#333333',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-size',
                        'profile_param_value' => '1920x1080',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-codec-bandwidth',
                        'profile_param_value' => '3mb',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-fps',
                        'profile_param_value' => '30',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-bgcolor',
                        'profile_param_value' => '#000000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                        'profile_param_value' => 'group:grid',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                        'profile_param_value' => '3x3',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-mode',
                        'profile_param_value' => 'mux',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'video-mcu-stereo-320',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for MCU Stereo & 320p',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => '$${outbound_caller_name}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => '$${outbound_caller_id}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'channels',
                        'profile_param_value' => '2',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'false',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'conference-flags',
                        'profile_param_value' => 'livearray-json-status|json-events|video-floor-only|rfc-4579|livearray-sync|minimize-video-encoding|manage-inbound-video-bitrate|video-required-for-canvas|video-mute-exit-canvas|mute-detect',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => '$${domain}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '200',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => '$${hold_music}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '48000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-auto-floor-msec',
                        'profile_param_value' => '1000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-bgcolor',
                        'profile_param_value' => '#333333',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-size',
                        'profile_param_value' => '480x320',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-codec-bandwidth',
                        'profile_param_value' => '3mb',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-fps',
                        'profile_param_value' => '30',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-bgcolor',
                        'profile_param_value' => '#000000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                        'profile_param_value' => 'group:grid',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                        'profile_param_value' => '3x3',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-mode',
                        'profile_param_value' => 'mux',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'video-mcu-stereo-480',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for MCU Stereo & 480p',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => '$${outbound_caller_name}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => '$${outbound_caller_id}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'channels',
                        'profile_param_value' => '2',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'false',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'conference-flags',
                        'profile_param_value' => 'livearray-json-status|json-events|video-floor-only|rfc-4579|livearray-sync|minimize-video-encoding|manage-inbound-video-bitrate|video-required-for-canvas|video-mute-exit-canvas|mute-detect',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => '$${domain}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '200',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => '$${hold_music}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '48000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-auto-floor-msec',
                        'profile_param_value' => '1000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-bgcolor',
                        'profile_param_value' => '#333333',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-size',
                        'profile_param_value' => '640x480',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-codec-bandwidth',
                        'profile_param_value' => '3mb',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-fps',
                        'profile_param_value' => '30',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-bgcolor',
                        'profile_param_value' => '#000000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                        'profile_param_value' => 'group:grid',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                    'profile_param_value' => '3x3',
                    'profile_param_enabled' => 'true',
                    'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-mode',
                    'profile_param_value' => 'mux',
                    'profile_param_enabled' => 'true',
                    'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'video-mcu-stereo-720',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for MCU Stereo & 720p',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => '$${outbound_caller_name}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => '$${outbound_caller_id}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'channels',
                        'profile_param_value' => '2',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'false',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'conference-flags',
                        'profile_param_value' => 'livearray-json-status|json-events|video-floor-only|rfc-4579|livearray-sync|minimize-video-encoding|manage-inbound-video-bitrate|video-required-for-canvas|video-mute-exit-canvas|mute-detect',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => '$${domain}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '200',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => '$${hold_music}',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '48000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-auto-floor-msec',
                        'profile_param_value' => '1000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-bgcolor',
                        'profile_param_value' => '#333333',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-canvas-size',
                        'profile_param_value' => '1280x720',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-codec-bandwidth',
                        'profile_param_value' => '3mb',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-fps',
                        'profile_param_value' => '30',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-bgcolor',
                        'profile_param_value' => '#000000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                        'profile_param_value' => 'group:grid',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-layout-name',
                        'profile_param_value' => '3x3',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'video-mode',
                        'profile_param_value' => 'mux',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'wait-mod',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings when you must wait for the moderator',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                        'profile_param_value' => 'conference/conf-alone.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'auto-gain-level',
                        'profile_param_value' => '0',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-controls',
                        'profile_param_value' => 'default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'cdr-log-dir',
                        'profile_param_value' => 'auto',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'true',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'conference-flags',
                        'profile_param_value' => 'wait-mod',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '15',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moderator-controls',
                        'profile_param_value' => 'moderator',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => 'local_stream://default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '8000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
            [
                'profile_name' => 'wideband',
                'profile_enabled' => 'true',
                'profile_description' => 'Settings for Wideband',
                'params' => [
                    [
                        'profile_param_name' => 'alone-sound',
                    'profile_param_value' => 'conference/conf-alone.wav',
                    'profile_param_enabled' => 'true',
                    'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'auto-gain-level',
                        'profile_param_value' => '0',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'bad-pin-sound',
                        'profile_param_value' => 'conference/conf-bad-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-controls',
                        'profile_param_value' => 'default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-name',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'caller-id-number',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'cdr-log-dir',
                    'profile_param_value' => 'auto',
                    'profile_param_enabled' => 'true',
                    'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'comfort-noise',
                        'profile_param_value' => 'true',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'domain',
                        'profile_param_value' => null,
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'energy-level',
                        'profile_param_value' => '15',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'enter-sound',
                        'profile_param_value' => 'tone_stream://%(200,0,500,600,700)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'exit-sound',
                        'profile_param_value' => 'tone_stream://%(500,0,300,200,100,50,25)',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'interval',
                        'profile_param_value' => '20',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-locked-sound',
                        'profile_param_value' => 'conference/conf-is-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'is-unlocked-sound',
                        'profile_param_value' => 'conference/conf-is-unlocked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'kicked-sound',
                        'profile_param_value' => 'conference/conf-kicked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'locked-sound',
                        'profile_param_value' => 'conference/conf-locked.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moderator-controls',
                        'profile_param_value' => 'moderator',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'moh-sound',
                        'profile_param_value' => 'local_stream://default',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'muted-sound',
                        'profile_param_value' => 'conference/conf-muted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'pin-sound',
                        'profile_param_value' => 'conference/conf-pin.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'rate',
                        'profile_param_value' => '16000',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                    [
                        'profile_param_name' => 'unmuted-sound',
                        'profile_param_value' => 'conference/conf-unmuted.wav',
                        'profile_param_enabled' => 'true',
                        'profile_param_description' => null,
                    ],
                ],
            ],
        ],
    ],
    'domains' => [
        'app_uuid' => env('DOMAIN_APP_UUID', 'b31e723a-bf70-670c-a49b-470d2a232f71'),
    ],
    'event_guard' => [
        'app_uuid' => env('EVENT_GUARD_APP_UUID', 'c5b86612-1514-40cb-8e2c-3f01a8f6f637'),
    ],
    'inbound_routes' => [
        'app_uuid' => env('INBOUND_ROUTE_APP_UUID', 'c03b422e-13a8-bd1b-e42b-b6b9b4d27ce4'),
    ],
    'install' => [
        'app_uuid' => env('INSTALL_APP_UUID', '75507e6e-891e-11e5-af63-feff819cdc9f'),
    ],
    'ivr_menus' => [
        'app_uuid' => env('IVR_MENU_APP_UUID', 'a5788e9b-58bc-bd1b-df59-fff5d51253ab'),
    ],
    'outbound_routes' => [
        'app_uuid' => env('OUTBOUND_ROUTE_APP_UUID', '8c914ec3-9fc0-8ab5-4cda-6c9288bdc9a3'),
    ],
    'time_conditions' => [
        'app_uuid' => env('TIME_CONDITION_APP_UUID', '4b821450-926b-175a-af93-a03c441818b1'),
    ],
    'queues' => [
        'app_uuid' => env('QUEUE_APP_UUID', '16589224-c876-aeb3-f59f-523a1c0801f7'),
    ],
    'ring_groups' => [
        'app_uuid' => env('RING_GROUP_APP_UUID', '1d61fb65-1eec-bc73-a6ee-a6203b4fe6f2'),
    ],

    // INSTALLATION PATHS
    'BSD' => [
        'config_path' => env('INSTALL_CONFIG_PATH', '/usr/local/etc/coolpbx'),
        'config_file' => env('INSTALL_CONFIG_FILE', '/usr/local/etc/coolpbx/config.conf'),
        'document_root' => env('DOCUMENT_ROOT', '/usr/local/www/coolpbx'),
        'old_config_path' => env('OLD_INSTALL_CONFIG_PATH', '/usr/local/etc/fusionpbx'),
        'old_config_file' => env('OLD_INSTALL_CONFIG_FILE', '/usr/local/etc/fusionpbx/config.conf'),
        'old_document_root' => env('OLD_DOCUMENT_ROOT', '/usr/local/www/fusionpbx'),
        'conf_dir' => env('INSTALL_CONF_DIR', '/usr/local/etc/freeswitch'),
        'sounds_dir' => env('INSTALL_SOUNDS_DIR', '/usr/share/freeswitch/sounds'),
        'database_dir' => env('INSTALL_DATABASE_DIR', '/var/lib/freeswitch/db'),
        'recordings_dir' => env('INSTALL_RECORDINGS_DIR', '/var/lib/freeswitch/recordings'),
        'storage_dir' => env('INSTALL_STORAGE_DIR', '/var/lib/freeswitch/storage'),
        'voicemail_dir' => env('INSTALL_VOICEMAIL_DIR', '/var/lib/freeswitch/storage/voicemail'),
        'scripts_dir' => env('INSTALL_SCRIPTS_DIR', '/usr/share/freeswitch/scripts'),
        'php_dir' => PHP_BINDIR,
        'cache_location' => env('INSTALL_CACHE_LOCATION', '/var/cache/coolpbx'),
        'old_cache_location' => env('OLD_INSTALL_CACHE_LOCATION', '/var/cache/fusionpbx'),
    ],
    'LIN' => [
        'config_path' => env('INSTALL_CONFIG_PATH', '/etc/coolpbx'),
        'config_file' => env('INSTALL_CONFIG_FILE', '/etc/coolpbx/config.conf'),
        'document_root' => env('DOCUMENT_ROOT', '/var/www/coolpbx'),
        'old_config_path' => env('OLD_INSTALL_CONFIG_PATH', '/etc/fusionpbx'),
        'old_config_file' => env('OLD_INSTALL_CONFIG_FILE', '/etc/fusionpbx/config.conf'),
        'old_document_root' => env('OLD_DOCUMENT_ROOT', '/var/www/fusionpbx'),
        'conf_dir' => env('INSTALL_CONF_DIR', '/etc/freeswitch'),
        'sounds_dir' => env('INSTALL_SOUNDS_DIR', '/usr/share/freeswitch/sounds'),
        'database_dir' => env('INSTALL_DATABASE_DIR', '/var/lib/freeswitch/db'),
        'recordings_dir' => env('INSTALL_RECORDINGS_DIR', '/var/lib/freeswitch/recordings'),
        'storage_dir' => env('INSTALL_STORAGE_DIR', '/var/lib/freeswitch/storage'),
        'voicemail_dir' => env('INSTALL_VOICEMAIL_DIR', '/var/lib/freeswitch/storage/voicemail'),
        'scripts_dir' => env('INSTALL_SCRIPTS_DIR', '/usr/share/freeswitch/scripts'),
        'php_dir' => PHP_BINDIR,
        'cache_location' => env('INSTALL_CACHE_LOCATION', '/var/cache/coolpbx'),
        'old_cache_location' => env('OLD_INSTALL_CACHE_LOCATION', '/var/cache/fusionpbx'),
    ],
    'WIN' => [
        'config_path' => env('INSTALL_CONFIG_PATH', $_SERVER["DOCUMENT_ROOT"].DIRECTORY_SEPARATOR.'resources'),
        'config_file' => env('INSTALL_CONFIG_FILE', $_SERVER["DOCUMENT_ROOT"].DIRECTORY_SEPARATOR.'resources'.DIRECTORY_SEPARATOR.'config.conf'),
        'document_root' => env('DOCUMENT_ROOT', $_SERVER["DOCUMENT_ROOT"]),
        'conf_dir' => env('INSTALL_CONF_DIR', $_SERVER['ProgramFiles'].DIRECTORY_SEPARATOR.'freeswitch'.DIRECTORY_SEPARATOR.'conf'),
        'sounds_dir' => env('INSTALL_SOUNDS_DIR', $_SERVER['ProgramFiles'].DIRECTORY_SEPARATOR.'freeswitch'.DIRECTORY_SEPARATOR.'sounds'),
        'database_dir' => env('INSTALL_DATABASE_DIR', $_SERVER['ProgramFiles'].DIRECTORY_SEPARATOR.'freeswitch'.DIRECTORY_SEPARATOR.'db'),
        'recordings_dir' => env('INSTALL_RECORDINGS_DIR', $_SERVER['ProgramFiles'].DIRECTORY_SEPARATOR.'freeswitch'.DIRECTORY_SEPARATOR.'recordings'),
        'storage_dir' => env('INSTALL_STORAGE_DIR', $_SERVER['ProgramFiles'].DIRECTORY_SEPARATOR.'freeswitch'.DIRECTORY_SEPARATOR.'storage'),
        'voicemail_dir' => env('INSTALL_VOICEMAIL_DIR', $_SERVER['ProgramFiles'].DIRECTORY_SEPARATOR.'freeswitch'.DIRECTORY_SEPARATOR.'voicemail'),
        'scripts_dir' => env('INSTALL_SCRIPTS_DIR', $_SERVER['ProgramFiles'].DIRECTORY_SEPARATOR.'freeswitch'.DIRECTORY_SEPARATOR.'scripts'),
        'php_dir' => dirname(PHP_BINARY),
        'cache_location' => env('INSTALL_CACHE_LOCATION', dirname($_SERVER['DOCUMENT_ROOT']).DIRECTORY_SEPARATOR.'cache'.DIRECTORY_SEPARATOR.'coolpbx'),
        'old_cache_location' => env('OLD_INSTALL_CACHE_LOCATION', dirname($_SERVER['DOCUMENT_ROOT']).DIRECTORY_SEPARATOR.'cache'.DIRECTORY_SEPARATOR.'fusionpbx'),
    ],
];
